### ISSUE TITLE
Not compatible with new BCH address type

### ISSUE THREAD

**Issue by 1baga** [ognus/wallet-address-validator#43] opened 2018-10-17 16:18 UTC
The module is not yet compatible with the new BCH address type that starts with 'q'

Please fix

**Comment by ognus** [comment] 2018-11-17 11:50
Thanks you for reporting and very sorry for late response. Duplicate of https://github.com/ognus/wallet-address-validator/issues/27

**Closed by ognus** 2018-11-17 11:50 UTC
Labels: duplicate
